## Manually picked points

In [168]:
# image pair 01
!python main.py \
    --manual \
    --dir_x1=./data/points/01_x1.txt \
    --dir_x2=./data/points/01_x2.txt

Testing x1:
[220. 218.   1.]
[245. 186.   1.]
[241. 285.   1.]
[467. 191.   1.]
[526. 147.   1.]
[592. 149.   1.]
[651. 157.   1.]
[692. 246.   1.]
Testing x2:
[206. 250.   1.]
[229. 216.   1.]
[226. 317.   1.]
[452. 222.   1.]
[513. 179.   1.]
[575. 180.   1.]
[635. 187.   1.]
[668. 277.   1.]

---------Matrix results---------

F by custom function:
[ 4.27921558e-07 -2.32945173e-04  4.01701313e-02]
[ 2.21166164e-04 -2.80947009e-05 -8.45147307e-02]
[-0.04481939  0.09881204  1.        ]

F_norm by custom function:
[ 3.81707687e-07 -1.95563911e-04  3.35735841e-02]
[ 1.85734790e-04 -2.35640605e-05 -7.10631077e-02]
[-0.03780898  0.08287581  1.        ]

F by OpenCV package:
[ 4.31497590e-07 -1.89856693e-04  3.25568160e-02]
[ 1.80383672e-04 -2.28598464e-05 -6.90281111e-02]
[-0.03675722  0.08044706  1.        ]


In [167]:
# image pair 02
!python main.py \
    --manual \
    --dir_x1=./data/points/02_x1.txt \
    --dir_x2=./data/points/02_x2.txt

Testing x1:
[234. 212.   1.]
[257. 180.   1.]
[254. 280.   1.]
[476. 186.   1.]
[539. 143.   1.]
[603. 144.   1.]
[662. 153.   1.]
[708. 244.   1.]
Testing x2:
[218. 242.   1.]
[241. 211.   1.]
[240. 314.   1.]
[464. 218.   1.]
[525. 176.   1.]
[589. 176.   1.]
[647. 185.   1.]
[682. 274.   1.]

---------Matrix results---------

F by custom function:
[ 2.27836125e-07 -2.66091795e-05  1.04663862e-02]
[ 2.80440997e-05  4.85347361e-06 -1.29007447e-02]
[-0.01218747  0.009503    1.        ]

F_norm by custom function:
[ 4.11525059e-07 -2.58994399e-05  1.04466958e-02]
[ 2.88608032e-05  2.99372128e-06 -1.29110093e-02]
[-0.01219211  0.0096048   1.        ]

F by OpenCV package:
[ 4.00390098e-07 -2.58979498e-05  1.04610246e-02]
[ 2.89646365e-05  2.77536344e-06 -1.29013926e-02]
[-0.01222673  0.0096668   1.        ]


## Automatically detected points

In [166]:
# image pair 01
!python main.py \
    --dir_img1=./data/non-rectified/01/im0.png \
    --dir_img2=./data/non-rectified/01/im1.png \
    --use_ransac \
    --min_data=8 \
    --min_close_data=20 \
    --max_iteration=5000 \
    --max_error=400

Number of points detected:  532

---------Matrix results---------

F by custom function:
[ 1.21877318e-06  9.99919823e-07 -8.51081969e-04]
[ 4.08259309e-06  2.14390929e-06 -2.89214942e-03]
[-0.00142445 -0.00101404  1.        ]

F_norm by custom function:
[ 5.12878647e-06  4.05445418e-05 -4.58328630e-03]
[-7.05749186e-05  7.62117411e-05 -1.89130298e-02]
[7.88929848e-03 9.90273215e-05 1.00000000e+00]

F by OpenCV package:
[ 5.12948775e-06  3.91317793e-05 -2.69754579e-03]
[-7.39268392e-05  8.50722454e-05 -2.97874441e-02]
[0.00707583 0.00935442 1.        ]

F by RANSAC:
[ 5.44742006e-06 -3.76959828e-05  1.46898894e-01]
[ 3.86338422e-05 -1.68161803e-06  7.21270530e-02]
[-0.15296805 -0.0718551   1.        ]


In [1]:
# image pair 01
!python main.py \
    --dir_img1=./data/non-rectified/01/im0.png \
    --dir_img2=./data/non-rectified/01/im1.png \
    --use_ransac \
    --min_data=8 \
    --min_close_data=20 \
    --max_iteration=5000 \
    --max_error=400

Number of points detected by SIFT:  532
Number of points used as good matches:  532

Number of inliers:  398
RANSAC succeeded

---------------Matrix results---------------


---1. By OpenCV function---

(1a) F_cv with best 8 points:
[ 9.89331473e-07 -1.59454382e-05  6.43092777e-02]
[2.45958203e-05 3.92108317e-06 2.02293533e-02]
[-0.06712649 -0.02495671  1.        ]

(1b) F_cv with all 398 inliers:
[ 2.50800401e-06 -4.12332756e-05  8.87127426e-02]
[4.54344028e-05 9.34839481e-07 2.76890878e-02]
[-0.09283515 -0.02917468  1.        ]


---2. With normalization---

(2a) F_norm with best 8 points:
[ 9.94005739e-07 -1.59950040e-05  6.44858428e-02]
[2.46586790e-05 3.94166359e-06 2.02668936e-02]
[-0.06729201 -0.02504264  1.        ]

(2b) F_norm with all 398 inliers:
[ 2.51102068e-06 -4.14254318e-05  8.86898331e-02]
[4.56113315e-05 9.42491390e-07 2.75420723e-02]
[-0.09280029 -0.02905577  1.        ]


---3. Without normalization---

(3a) F with best 8 points:
[ 1.92855201e-06 -1.64780168e-05  6

In [1]:
# image pair 01
!python main.py \
    --dir_img1=./data/non-rectified/01/im0.png \
    --dir_img2=./data/non-rectified/01/im1.png \
    --use_ransac \
    --min_data=8 \
    --min_close_data=20 \
    --max_iteration=5000 \
    --max_error=400

Number of points detected by SIFT:  532
Number of points used as good matches:  532

Number of inliers:  230
RANSAC succeeded

---------------Matrix results---------------


---1. By OpenCV function---

(1a) F_cv with best 8 points:
[-6.42848091e-06 -1.80465493e-04 -5.17851622e-02]
[ 1.76276804e-04  4.42317786e-06 -9.18674411e-02]
[0.05087404 0.09125052 1.        ]

(1b) F_cv with all 230 inliers:
[ 3.52709413e-06 -1.32682193e-04 -4.64119207e-02]
[ 1.27289694e-04 -7.65580565e-06 -7.24949319e-02]
[0.04305682 0.07355146 1.        ]


---2. With normalization---

(2a) F_norm with best 8 points:
[-6.78331573e-06 -1.91721530e-04 -5.48414154e-02]
[ 1.86950753e-04  7.08250916e-06 -9.72409446e-02]
[0.05379819 0.09710729 1.        ]

(2b) F_norm with all 230 inliers:
[ 3.50026523e-06 -1.30345858e-04 -4.47511340e-02]
[ 1.25202636e-04 -7.61081823e-06 -7.10855143e-02]
[0.04141466 0.07207942 1.        ]


---3. Without normalization---

(3a) F with best 8 points:
[-2.02217867e-05 -1.17733131e-04 -3

In [81]:
# add the argument --use_ssd, to compute result also with SSD
!python disparity.py \
    --dir_img1=./data/rectified/01/im0.png \
    --dir_img2=./data/rectified/01/im1.png \
    --result_dir=./result/01 \
    --use_ssd \
    --block_size=5 \
    --minDisparity=0 \
    --numDisparity=16 \
    --disp12MaxDiff=1 \
    --uniquenessRatio=10 \
    --speckleWindowSize=100 \
    --speckleRange=32

Calculated Disparity at 0 row
Calculated Disparity at 1 row
Calculated Disparity at 2 row
Calculated Disparity at 3 row
Calculated Disparity at 4 row
Calculated Disparity at 5 row
Calculated Disparity at 6 row
Calculated Disparity at 7 row
Calculated Disparity at 8 row
Calculated Disparity at 9 row
Calculated Disparity at 10 row
Calculated Disparity at 11 row
Calculated Disparity at 12 row
Calculated Disparity at 13 row
Calculated Disparity at 14 row
Calculated Disparity at 15 row
Calculated Disparity at 16 row
Calculated Disparity at 17 row
Calculated Disparity at 18 row
Calculated Disparity at 19 row
Calculated Disparity at 20 row
Calculated Disparity at 21 row
Calculated Disparity at 22 row
Calculated Disparity at 23 row
Calculated Disparity at 24 row
Calculated Disparity at 25 row
Calculated Disparity at 26 row
Calculated Disparity at 27 row
Calculated Disparity at 28 row
Calculated Disparity at 29 row
Calculated Disparity at 30 row
Calculated Disparity at 31 row
Calculated Dispari

In [86]:
import numpy as np
import cv2

In [84]:
disp = np.load('./result/01\ssd.npy')

In [88]:
cv2.imshow('disp', disp)
cv2.waitKey(0)

-1

In [89]:
disp

array([[[  24.,   24.,   24.],
        [  35.,   35.,   35.],
        [  35.,   35.,   35.],
        ...,
        [   1.,    1.,    1.],
        [-940., -940., -940.],
        [-941., -941., -941.]],

       [[   1.,    1.,    1.],
        [  35.,   35.,   35.],
        [  14.,   14.,   14.],
        ...,
        [   1.,    1.,    1.],
        [-940., -940., -940.],
        [-941., -941., -941.]],

       [[   1.,    1.,    1.],
        [   1.,    1.,    1.],
        [  24.,   24.,   24.],
        ...,
        [   1.,    1.,    1.],
        [-940., -940., -940.],
        [-941., -941., -941.]],

       ...,

       [[   0.,    0.,    0.],
        [   0.,    0.,    0.],
        [   0.,    0.,    0.],
        ...,
        [   0.,    0.,    0.],
        [   0.,    0.,    0.],
        [   0.,    0.,    0.]],

       [[   0.,    0.,    0.],
        [   0.,    0.,    0.],
        [   0.,    0.,    0.],
        ...,
        [   0.,    0.,    0.],
        [   0.,    0.,    0.],
        [   0.,